### ISSUE TITLE
[문의] 서류 불합 안내에 관한 건

### ISSUE THREAD

**Issue by Larshavin** [lokks307/recruit#41]
안녕하세요

최근 사람인 사이트를 통해 (또한 [이메일](recruit@caresquare.kr)을 통해서도)
병역특례(현역전직)를 지원한 양성연이라고 합니다.

채용 과정에 있어 몇 가지를 여쭙고 싶어서 글을 남겨 봅니다.

우선 첫 번째로, 
마음의 준비를 하고 있긴 하지만,
서류 탈락자에게도 합불 여부가 안내 되는지 궁금합니다.

만약 불합격도 통보가 되는 것이라면,
저의 경우에 전문연구요원 현역 전직의 시기가 올해 11월 3일 이후 가능하게 됩니다.
그 시기에 비해 조금 일찍 서류를 접수하였는데, 이 부분이 괜찮을지 여쭙고 싶습니다.

마지막으로, 저는 천문대기과학과에서 수치상대론을 전공하였는데 
이 부분이 혹시 병무청 전직 승인과 관련 또는 회사 채용 방침에 문제가 될지 궁금합니다.
(현재 근무 중인 병역지정업체는 IT 기업의 부설 연구소 입니다)

감사합니다.

**Comment by doscode-kr** [comment]
안녕하세요 @Larshavin 님, 저희 회사에 관심을 갖고 문의해주셔서 감사합니다.
최근 회사 업무가 상당해서 즉시 안내를 드리지 못한 점이 있었습니다.
오늘 서류전형 안내 메일을 보내드리도록 할게요.

기다려주셔서 감사합니다
